# Generated by Django 3.2.23 on 2023-11-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.basketmodel'),
        ),
    ]
